# Generated by Django 4.0.2 on 2022-02-26 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kontrak', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rab',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='rab',
            name='unit',
        ),
        migrations.AddField(
            model_name='rab',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='kontrak.unit'),
        ),
        migrations.RemoveField(
            model_name='rab',
            name='work_item',
        ),
        migrations.AddField(
            model_name='rab',
            name='work_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='kontrak.workitem'),
        ),
        migrations.RemoveField(
            model_name='workitem',
            name='cost_acc',
        ),
        migrations.AddField(
            model_name='workitem',
            name='cost_acc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='kontrak.costacc'),
        ),
        migrations.RemoveField(
            model_name='workitem',
            name='unit',
        ),
        migrations.AddField(
            model_name='workitem',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='kontrak.unit'),
        ),
    ]
