# Generated by Django 4.0.2 on 2022-02-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontrak', '0002_alter_rab_start_date_remove_rab_unit_rab_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rab',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
