# Generated by Django 4.0.2 on 2022-02-27 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kontrak', '0003_alter_rab_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rab',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='rab',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='rab',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='rab',
            name='volume',
        ),
        migrations.RemoveField(
            model_name='rab',
            name='work_item',
        ),
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rab',
            name='name',
            field=models.CharField(default='RAB Total', max_length=255, verbose_name='Nama RAB'),
        ),
        migrations.AddField(
            model_name='rab',
            name='phase',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='costacc',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='kontrak.client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='cost_acc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='kontrak.costacc'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='kontrak.unit'),
        ),
        migrations.CreateModel(
            name='VolAndTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('rab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kontrak.rab')),
                ('work_item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='kontrak.workitem')),
            ],
        ),
    ]
